
common:
  image: ghcr.io/mycel-domain/mycel:main
  binaryName: myceld
  genesis: '{}'
  snapshotInterval: 20

seed:
  volumeSize: 256Gi
  node_key: '{}'
  priv_key: '{}'

node:
  volumeSize: 256Gi
  replicas: 0

ingress:
  enable: true
  lcd_endpoint: lcd.example.com
  rpc_endpoint: rpc.example.com

