{{ if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: mycel-node
spec:
  rules:
    # lcd
    - host: {{ .Values.ingress.lcd_endpoint }}
      http:
        paths:
          - backend:
              service:
                name: mycel-node
                port:
                  number: 1317
            path: /
            pathType: Prefix

    # rpc
    - host: {{ .Values.ingress.rpc_endpoint }}
      http:
        paths:
          - backend:
              service:
                name: mycel-node
                port:
                  number: 26657
            path: /
            pathType: Prefix

    # p2p
    - host: {{ .Values.ingress.p2p }}
      http:
        paths:
          - backend:
              service:
                name: mycel-node
                port:
                  number: 26656
            path: /
            pathType: Prefix

  tls:
    - hosts:
        - {{ .Values.ingress.lcd_endpoint }}
        - {{ .Values.ingress.rpc_endpoint }}
        - {{ .Values.ingress.p2p_endpoint }}
      secretName: mycel-node-ingress-cert
{{ end }}
