apiVersion: v1
kind: Service
metadata:
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.seed_endpoint }}
  name: mycel-seed
spec:
  selector:
    app: mycel-seed
  ports:
  - name: p2p
    port: 26656
    protocol: TCP
  - name: rpc
    port: 26657
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.ingress.enable }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.lcd_endpoint }},{{ .Values.ingress.rpc_endpoint }}"
  {{- end }}
  name: mycel-node
spec:
  selector:
    app: mycel-node
  ports:
  - name: api
    port: 1317
    protocol: TCP
  - name: rosetta
    port: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    protocol: TCP
  - name: p2p
    port: 26656
    protocol: TCP
  - name: rpc
    port: 26657
    protocol: TCP
  - name: grpc-web
    port: 9091
    protocol: TCP
  type: ClusterIP

