apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mycel-seed
spec:
  selector:
    matchLabels:
      app: mycel-seed
  serviceName: "mycel-seed"
  replicas: 1
  template:
    metadata:
      labels:
        app: mycel-seed
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mycel
        image: {{ .Values.seed.image }}
        volumeMounts:
        - name: data
          mountPath: /opt/data
        ports:
          - containerPort: 1317
            name: api
          - containerPort: 8080
            name: rosetta
          - containerPort: 9090
            name: grpc
          - containerPort: 26657
            name: rpc
          - containerPort: 9091
            name: grpc-web
        command:
          - sh
          - -c
          - |
            {{ .Values.seed.binaryName }} start --home /opt/data/mycel
      initContainers:
      - name: init-seed
        image: golang
        volumeMounts:
        - name: data
          mountPath: /opt/data
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 10Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 10Gi
            memory: 2Gi
        command:
          - bash
          - -cx
          - |
            if [ -d /opt/data/mycel ]; then
              exit 0;
            fi
            curl 'https://get.ignite.com/cli@'{{ .Values.ignite.version }}! | bash
            mkdir work
            cd work
            git clone {{ .Values.seed.repositoryURL }} .
            ignite chain init --home /opt/data/mycel

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

